version: 1
disable_existing_loggers: false
formatters:
  fileFormatter:
    format: '%(asctime)s:%(name)s:%(levelname)s:%(message)s'
handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: fileFormatter
    stream: ext://sys.stdout
  fileHandler:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    filename: './logs/metrics_measurement.log'
    formatter: fileFormatter
    when: 'midnight'
    interval: 1
    backupCount: 7
  errorFileHandler:
    class: logging.handlers.TimedRotatingFileHandler
    level: ERROR
    filename: "./logs/metrics_measurement_error.log"
    formatter: fileFormatter
    when: 'midnight'
    interval: 1
    backupCount: 7
loggers:
  exampleLogger:
    level: DEBUG
    handlers: [consoleHandler, fileHandler, errorFileHandler]
    propagate: No
root:
  level: DEBUG
  handlers: [consoleHandler, fileHandler, errorFileHandler]